spring:
  application:
    name: Tasks

  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.mail.ru
    port: 465
    username: ivanoff-m@list.ru
    password: DzrPjc7h6cxNNkEKxVsY
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

notification:
  mail:
    to: ivanoff-m@list.ru

logging:
  level:
    org.springframework: INFO
    com.example.tasks.kafka: DEBUG

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group-id: test_group
  producer:
    enable: true
  session_timeout_ms: 15000
  max_partition:
    fetch:
      bytes: 300000
  max:
    poll:
      records: 1
      interval:
        ms: 10000
  topic:
    task_status_changed: tasks_status_changing
  listener:
    poll-timeout: 1000
